### ISSUE TITLE
Repository: add input validation

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3dServerRepository#1]
The register method must validate what it's sent before adding the server to the list.

**Comment by cwbooth5** [comment]
What specifically is it looking at and what should the conditions be?

**Comment by Wavesonics** [comment]
**name:** Must be between 3 and 32 characters (strip and dont count white space)
**ip:** Must be a valid IP address (also strip whitespace)
**port:** Must be a valid port

**Comment by Wavesonics** [comment]
Around line 35, validate all of the inputs, and if they don't all check out, don't add the server to the list, and return an error message (and error code) to the requester.

**Comment by cwbooth5** [comment]
OK I got it returning a 400 error back to the user with an error in all three conditions. I'll clean it up later today and check in. This is fun.

Actually...

This is `func fun() string { fmt.Prntln("fun")}`

**Comment by Wavesonics** [comment]
😆
