### ISSUE TITLE
Repository: prune servers in background

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3dServerRepository#2]
Pruning should happen periodically in the background.

It should not be tied to any request.

This prevents scalability issues.

In order for this to work, access to the serverList map must be protected with a Mutex. Preferably a read/write lock, so that multiple reads can execute in parallel, but a write will block everyone from accessing it.

I don't know if Go has a read/write lock built in. Worst case we can just use a straight Mutex to lock access to it when anyone is doing anything.

**Comment by cwbooth5** [comment]
Or in an async thread for the entire duration of the main thread's execution?

**Comment by Wavesonics** [comment]
Ya that would work

**Comment by Wavesonics** [comment]
@cwbooth5 updated this task to reflect what we talked about on Telegram.
