### ISSUE TITLE
Repository: add /getip end point

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3dServerRepository#3]
Right now we use the service ipify.org

However if we ever had to scale up, that would start to cost us money. Also we are not in control of it and it could die when ever.

Since we're already running a web service of our own, we might as well just implement this our selves so we'll be self sufficient.

The end point should return a json payload with the field "ip" which contains a string of the ipv4 IP of the requestor.

We need to look and see if the HTTP server library we're using (Gin) will allow us to extract that information.

**Comment by Wavesonics** [comment]
eh? https://golangcode.com/get-the-request-ip-addr/

**Comment by Wavesonics** [comment]
eh?? https://github.com/gin-gonic/gin/blob/master/context.go#L710

**Comment by cwbooth5** [comment]
That would do it. You don't actually have to use HTTP layer information. We can grab this off the socket. I think gin just does that for you. We can easily see the source IP of all requests coming in.

They would still have to provide a port we'd contact them back on though. Whatever they are forwarding through their router ingress.

That initial TCP connection they make to the repo:8080 is going to originate from some other high random ephemeral source port so we can't rely on that. We'd have to combine the IP we found as the source and the port they specified in the JSON.

I suggest if they don't provide an IP in the JSON payload, we just infer it from the one they originate from. THoughts?

**Comment by cwbooth5** [comment]
And yes there are zero reasons to keep using ipify at this point.
