### ISSUE TITLE
Repository: Add /remove endpoint

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3dServerRepository#7]
it should accept an IP payload, and then remove the entry for that server in the map.

**Comment by Wavesonics** [comment]
Once this is added, the Server will call this when it goes into a game. no one should join.

We could use HTTP verbs here: DELETE

**Comment by cwbooth5** [comment]
Yes the delete verb is appropriate for this. Let me see what I can craft.

**Comment by cwbooth5** [comment]
JSON coming in from the client is going to be just a string? Or is it going to be:

`{"ip": "1.2.3.4"}`

?

**Comment by Wavesonics** [comment]
`{"ip": "1.2.3.4", "port": "31000"}`

**Comment by Wavesonics** [comment]
This is deployed now right @cwbooth5 ?

**Comment by cwbooth5** [comment]
Yeah I deployed it. How is it working? Anything lookin borked?

**Comment by Wavesonics** [comment]
It's all good!
